package dev.overgrown.apoli.power;

import dev.overgrown.apoli.Apoli;
import net.minecraft.resources.ResourceLocation;

public final class ApoliIds {
    public static final ResourceLocation GROUNDED = Apoli.id("grounded");
    public static final ResourceLocation SWIMMING = Apoli.id("swimming");
    public static final ResourceLocation CLIMBING = Apoli.id("climbing");
    public static final ResourceLocation PHASING = Apoli.id("phasing");
    public static final ResourceLocation INVISIBILITY = Apoli.id("invisibility");
    public static final ResourceLocation ELYTRA_FLIGHT = Apoli.id("elytra_flight");
    public static final ResourceLocation DISABLE_REGEN = Apoli.id("disable_regen");
    public static final ResourceLocation MODIFY_HARVEST = Apoli.id("modify_harvest");
    public static final ResourceLocation PREVENT_TELEPORT = Apoli.id("prevent_teleport");
    public static final ResourceLocation PREVENT_USE = Apoli.id("prevent_use");
    public static final ResourceLocation ENTITY_GLOW = Apoli.id("entity_glow");
    public static final ResourceLocation RESTRICT_ARMOR = Apoli.id("restrict_armor");
    public static final ResourceLocation PREVENT_GAME_EVENT = Apoli.id("prevent_game_event");
    public static final ResourceLocation PREVENT_SLEEP = Apoli.id("prevent_sleep");
    public static final ResourceLocation WALK_ON_FLUID = Apoli.id("walk_on_fluid");
    public static final ResourceLocation IGNORE_FLUID = Apoli.id("ignore_fluid");
    public static final ResourceLocation STARTING_EQUIPMENT = Apoli.id("starting_equipment");
    public static final ResourceLocation MODIFY_FALLING = Apoli.id("modify_falling");
    public static final ResourceLocation MODIFY_AIR_SPEED = Apoli.id("modify_air_speed");
    public static final ResourceLocation MODIFY_STATUS_EFFECT_AMPLIFIER = Apoli.id("modify_status_effect_amplifier");
    public static final ResourceLocation MODIFY_STATUS_EFFECT_DURATION = Apoli.id("modify_status_effect_duration");
    public static final ResourceLocation NIGHT_VISION = Apoli.id("night_vision");
    public static final ResourceLocation FLUID_VISION = Apoli.id("fluid_vision");
    public static final ResourceLocation MODIFY_CAMERA_SUBMERSION = Apoli.id("modify_camera_submersion");
    public static final ResourceLocation MODIFY_VELOCITY = Apoli.id("modify_velocity");
    public static final ResourceLocation MODIFY_EXHAUSTION = Apoli.id("modify_exhaustion");
    public static final ResourceLocation MODIFY_DAMAGE = Apoli.id("modify_damage");
    public static final ResourceLocation ACTION_ON_HIT = Apoli.id("action_on_hit");
    public static final ResourceLocation ACTION_WHEN_HIT = Apoli.id("action_when_hit");
    public static final ResourceLocation ACTION_ON_COLLISION = Apoli.id("action_on_collision");
    public static final ResourceLocation REPLACE_SOUND_EMISSION = Apoli.id("replace_sound_emission");
    public static final ResourceLocation REPLACE_SOUND_RECEPTION = Apoli.id("replace_sound_reception");
    public static final ResourceLocation MODIFY_CRAFTING = Apoli.id("modify_crafting");
    public static final ResourceLocation ACTION_ON_SPEAK = Apoli.id("action_on_speak");
    public static final ResourceLocation ACTION_ON_REPLY = Apoli.id("action_on_reply");
    public static final ResourceLocation ACTION_ON_SENDING_MESSAGE = Apoli.id("action_on_sending_message");
    public static final ResourceLocation ACTION_ON_SPEECH = Apoli.id("action_on_speech");
    public static final ResourceLocation ACTION_ON_KEY_SEQUENCE = Apoli.id("action_on_key_sequence");
    public static final ResourceLocation ACTION_ON_SCROLL_WHEEL = Apoli.id("action_on_scroll_wheel");
    public static final ResourceLocation ACTION_ON_MOUSE_MOVEMENT = Apoli.id("action_on_mouse_movement");
    public static final ResourceLocation SHOW_BOTH_ARMS = Apoli.id("show_both_arms");
    public static final ResourceLocation EMISSIVE = Apoli.id("emissive");
    public static final ResourceLocation CREATIVE_FLIGHT = Apoli.id("creative_flight");
    public static final ResourceLocation PREVENT_FEATURE_RENDER = Apoli.id("prevent_feature_render");
    public static final ResourceLocation PREVENT_BLOCK_USE = Apoli.id("prevent_block_use");
    public static final ResourceLocation ACTION_ON_BLOCK_USE = Apoli.id("action_on_block_use");
    public static final ResourceLocation ACTION_ON_BLOCK_BREAK = Apoli.id("action_on_block_break");
    public static final ResourceLocation ACTION_ON_BLOCK_PLACE = Apoli.id("action_on_block_place");
    public static final ResourceLocation PREVENT_BLOCK_PLACE = Apoli.id("prevent_block_place");
    public static final ResourceLocation MODIFY_BREAK_SPEED = Apoli.id("modify_break_speed");
    public static final ResourceLocation MODIFY_JUMP = Apoli.id("modify_jump");
    public static final ResourceLocation MODIFY_BLOCK_STUCK_SPEED = Apoli.id("modify_block_stuck_speed");
    public static final ResourceLocation MODIFY_HEALING = Apoli.id("modify_healing");
    public static final ResourceLocation SCARE_MOBS = Apoli.id("scare_mobs");
    public static final ResourceLocation MODIFY_SWIM_SPEED = Apoli.id("modify_swim_speed");
    public static final ResourceLocation WATER_BREATHING = Apoli.id("water_breathing");
    public static final ResourceLocation PREVENT_ENTITY_RENDER = Apoli.id("prevent_entity_render");
    public static final ResourceLocation PREVENT_ENTITY_SELECTION = Apoli.id("prevent_entity_selection");
    public static final ResourceLocation PREVENT_BLOCK_SELECTION = Apoli.id("prevent_block_selection");
    public static final ResourceLocation ACTION_ON_WAKE_UP = Apoli.id("action_on_wake_up");
    public static final ResourceLocation MODIFY_BLOCK_RENDER = Apoli.id("modify_block_render");
    public static final ResourceLocation EDIBLE_ITEM = Apoli.id("edible_item");
    public static final ResourceLocation MODIFY_FOOD = Apoli.id("modify_food");
    public static final ResourceLocation MODIFY_TYPE_TAG = Apoli.id("modify_type_tag");
    public static final ResourceLocation MODIFY_PLAYER_SPAWN = Apoli.id("modify_player_spawn");
    public static final ResourceLocation PREVENT_ITEM_USE = Apoli.id("prevent_item_use");
    public static final ResourceLocation ITEM_ON_ITEM = Apoli.id("item_on_item");
    public static final ResourceLocation PREVENT_KEY_PRESS = Apoli.id("prevent_key_press");
    public static final ResourceLocation MODIFY_BOUNCINESS = Apoli.id("modify_bounciness");

    private ApoliIds() {}
}
